MODEL:
  ARCHITECTURE: "MMN"
  MMN:
    NUM_CLIPS: 128
    JOINT_SPACE_SIZE: 512
    FEATPOOL:
      INPUT_SIZE: 1024
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15,8,8,8]
    TEXT_ENCODER:
      NAME: 'BERT'
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 3
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.3
      MAX_IOU: 0.7
      NUM_POSTIVE_VIDEO_PROPOSAL: 3
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.05
      TAU_SENT: 0.05
      MARGIN: 0.1
      CONTRASTIVE_WEIGHT: 0.1
DATASETS:
  NAME: "makep"
  TRAIN: ("makeup_train",)
  TEST: ("makeup_test",)
INPUT:
  NUM_PRE_CLIPS: 256
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 8
  MILESTONES: (130, 190)
  MAX_EPOCH: 45
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 28
  FREEZE_BERT: 4
  ONLY_IOU: 7
  SKIP_TEST: 0
TEST:
  NMS_THRESH: 0.4
  BATCH_SIZE: 48
  CONTRASTIVE_SCORE_POW: 0.3

